### ISSUE TITLE
column number, window number and buffer number option

### ISSUE THREAD

**Issue by tripurari001** [tomdaly/vim-statusline-generator#1]
Hi 
I think the project is great and very useful

here are the some things I thought you might want to add 

- column number
- window number
- buffer number

what do you think ?

**Comment by lmintmate** [comment]
Since this appears to be a feature request, it would be nice to also add the keymap indication. For the record, according to `:h 'statusline'`, keymap is k, column number is c, and buffer number is n, so these should be easy to add. On the other hand, I don't know what @tripurari001 means with "window number" (number of each on-screen pane created by `:sp` perhaps?), but that one might need some additional work to add since there doesn't appear to be a ready-made option in `:h 'statusline'`.
Thank you tomdaly for creating this great utility, and thanks in advance for your understanding. Hope you don't mind me using this existing issue to make my own feature request (I figured that since this was a feature request, I might as well make my own here in order to not needlessly create a new issue. Hope that isn't a bother).

**Comment by tomdaly** [comment]
Thanks for the feedback; I'll start work on adding the column/window/buffer numbers and keymap indicators.

**Comment by tripurari001** [comment]
@tomdaly @lmintmate  by window number I meant the return value of `winnr()` without any argument 
this actually indicate split-windows number in current tab this is helpful in navigating quickly between windows for example I can do `<leader> n` ( where n is window number )

**Comment by lmintmate** [comment]
Thanks for making these changes @tomdaly - just saw the new version of the website. Just a small correction however: the preview string of the keymap on the website (currently `gb`) isn't accurate to how it is rendered on the vim statusline, as there the keymap is rendered like so `<gb>` (with the chevrons). This should probably be corrected, as to not confuse users of the generator that will see this rendered differently inside vim. Thanks again in advance for your understanding.

**Comment by tomdaly** [comment]
@lmintmate thanks for the reply, just modified the commit to include the chevrons which should update the website
